# Generated by Django 5.0.7 on 2024-12-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now  # Import `now` for default timestamp value


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                # Use `default=now` to populate existing rows with the current timestamp
                ('earned_at', models.DateTimeField(auto_now_add=True, default=now)),  
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
