# Generated by Django 5.0.7 on 2024-12-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_badge_earned_at_activity_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.AddField(
            model_name='activity',
            name='emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
