# Generated by Django 5.0.7 on 2024-12-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_recommendation_activity_emissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='emissions',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timestamp',
        ),
    ]
