# Generated by Django 5.0.7 on 2024-12-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_badge_timestamp_badge_earned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
